server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://onclass.ctwucaywofto.us-east-2.rds.amazonaws.com/onclass_bootcamp
    username: ${username}
    password: ${password}

  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: ${secret}
logging:
  level:
    org:
      springframework:
        security: TRACE
springdoc:
  swagger-ui:
    path: /doc/swagger-ui/index.html
  api-docs:
    path: /v3/api-docs